apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonball-quarkus-api-native
  labels:
    app: dragonball-quarkus-api-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonball-quarkus-api-native
  template:
    metadata:
      labels:
        app: dragonball-quarkus-api-native
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/q/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: dragonball-quarkus-api-native
          image: carlos89/dragonball-quarkus-api-native:latest # Asumiendo tag latest
          # IMPORTANTE: IfNotPresent asegura que use la imagen cargada localmente
          # en lugar de intentar descargarla de internet (y fallar).
          imagePullPolicy: IfNotPresent
          env:
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
            - name: QUARKUS_APPLICATION_NAME
              value: "dragonball-quarkus-api-native"
            #- name: QUARKUS_OTEL_EXPORTER_OTLP_ENABLED
            #  value: "true"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "128Mi" # Las im√°genes nativas consumen muy poca RAM
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: dragonball-quarkus-api-native
  labels:
    app: dragonball-quarkus-api-native
spec:
  selector:
    app: dragonball-quarkus-api-native
  type: NodePort
  ports:
    - name: http-api
      port: 80       # Puerto expuesto en el servicio
      targetPort: 8080 # Puerto de tu contenedor Quarkus