name: Build and Deploy to GKE Autopilot

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1 # Cambia esto a tu región
  REPOSITORY: dragonball-quarkus-api-repo
  IMAGE: dragonball-quarkus-api-native-gke
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1 # Cambia esto (zona o región del cluster)

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Autenticación GCP (Igual que antes)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Configurar Docker para Artifact Registry
      - name: Docker configuration
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # 3. Construir y Subir Imagen Nativa
      # NOTA: Ya no ejecutamos 'mvn package' fuera. El Dockerfile lo hace.
      # Usamos el flag -f para apuntar a tu archivo en la carpeta docker/
      - name: Build and Push Docker Image
        run: |-
          docker build -f docker/Dockerfile.native-micro \
            -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" .
          
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

      # 4. Obtener credenciales GKE
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # 5. Desplegar
      - name: Deploy to GKE
        run: |-
          export IMAGE_NAME="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          envsubst < k8s/deployment-native-gke.yaml | kubectl apply -f -
          kubectl rollout status deployment/dragonball-quarkus-api-native-gke